version: "3.5"
services:

  app:
    image: gcr.io/beyond-pricing-1024/beyonder:latest
#    image: node:latest
    restart: always
#    env_file:
#      - var.env
    command: npm run dev
    volumes:
      - ./pages:/app/pages
      - ./src:/app/src
      - ./public:/app/public
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./server.js:/app/server.js
      - ./socket.js:/app/socket.js

    ports:
      - "4998:4998"

